version: 0.0

#어떤 OS위한 배포파일인가?
os: linux

#다운받은 배포파일은 임시폴더에 저장되는데, 이를 어디로 옮길것인지?
files:
  - source: /
    destination: /var/www


#배포시 발생하는 생명주기마다 원하는 스크립트 실행 후크 제공
#실행할 스크립트들은 scripts폴더 내에 두고 보관한다.
hooks:
  #프로젝트 다운 뒤 배포 원하는 경로에 파일을 옮기기 전.
  BeforeInstall:
    - location: scripts/UnzipResourceBundle.sh
    - location: scripts/UnzipDataBundle.sh

  #파일을 모두 이동한 후 실행되는 스크립트들
  #Timeout 옵션은 190초 내에 스크립트 실행이 완료되지 않으면 실패로 간주한다.
  AfterInstall:
    - location: scripts/RestartServer.sh
      timeout: 190

