version: 0.0

#어떤 OS위한 배포파일인가?
os: linux

#다운받은 배포파일은 임시폴더에 저장되는데, 이를 어디로 옮길것인지?
files:
  - source: /
    destination: /home/ubuntu


#배포시 발생하는 생명주기마다 원하는 스크립트 실행 후크 제공
#실행할 스크립트들은 scripts폴더 내에 두고 보관한다.
#실행권한을 추가해야한다.
#git update-index --chmod=+x <스크립트 파일 이름>
hooks:
  #프로젝트 다운 뒤 배포 원하는 경로에 파일을 옮기기 전.
  # BeforeInstall:

  #파일을 모두 이동한 후 실행되는 스크립트들
  #Timeout 옵션은 시간 내에 스크립트 실행이 완료되지 않으면 실패로 간주한다.
  AfterInstall:
    - location: moim_back/scripts/InstallDependency.sh
    - location: moim_back/scripts/BuildServer.sh

  #어플리케이션 시작할 때 사용하는 스크립트
  #서버 시작하고 최대 20초 기다린다.
  ApplicationStart:
    - location: moim_back/scripts/StartServer.sh
      timeout: 20

  #서비스 재시작하고 서비스 올바르게 실행되는지 확인.
  #runas 옵션으로 사용자가 ec2-user가 아닌 codedeployer라는 유저로 실행되게한다.
# validateService:
#   - location: moim_back/scripts/validateService.sh
#     timeout: 30
#     runas: codedeployer

